name: industrial_taxonomy
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.8
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - jupyterlab
  - ipython
  - altair
  - clang_osx-64  # [not linux]
  - gcc_linux-64  # [not darwin]
  - metaflow
  # Put any conda dependencies here
  - graph-tool

  - pip:
    # Put any pip dependencies here (and no conda ones anywhere below)
    - altair_saver
    - sh
    - s3fs
    - spacy
    - gensim
    - nltk
    - altair_saver
    - sh
    - git+https://github.com/nestauk/research_daps@24_topsbm
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.0.0/en_core_web_lg-3.0.0.tar.gz

  # Tooling requirements (don't edit)
    - tornado>=5.0  # Stops luigi breaking jupyter
    - pandoc
    - pandoc-crossref
    - filelock
  - tqdm
  - pyyaml
  - pytables
  - black
  - blackcellmagic
  - pymysql
  - sqlalchemy
  - click
  - Sphinx
  - sphinxcontrib-napoleon
  - coverage
  - awscli
  - flake8
  - flake8-black
  - python-dotenv>=0.5.1
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jq
  - pytest
  - mypy
  - jupytext
