name: industrial_taxonomy
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.8
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - jupyterlab
  - ipython
  - altair
  - clang_osx-64  # [not linux]
  - gcc_linux-64  # [not darwin]
  - metaflow
  - xlrd
  - umap-learn
  # Put any conda dependencies here

  - pip:
    # Put any pip dependencies here (and no conda ones anywhere below)

  # Tooling requirements (don't edit)
    - tornado>=5.0  # Stops luigi breaking jupyter
  - tqdm
  - pyyaml
  - pytables
  - black
  - blackcellmagic
  - pymysql
  - sqlalchemy
  - click
  - Sphinx
  - sphinxcontrib-napoleon
  - coverage
  - awscli
  - flake8
  - flake8-black
  - python-dotenv>=0.5.1
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jq
  - pytest
  - mypy
  - jupytext
  - sentence-transformers
