flows:
  companies_house:
    run_id: 890
  glass:
    run_id: 414
  nlp_flow:
    params:
      n-gram: 3
      n-process: 2
    run_id: 1111
  glass_desc_preproc:
    params:
      n_docs: 100000
      n_gram: 2
      test_mode: false
    run_id: 1012
  topsbm:
    params:
      n_docs: -1
    run_id: 1025
  sic:
    run_id: 1059
params:
  match_threshold: 75
