flows:
  companies_house:
    run_id: 890
  glass:
    run_id: 414
  nlp_flow:
    params:
      n-gram: 3
      n-process: 2
    run_id: 1111
  sic:
    run_id: 1059
  topsbm:
    params:
      n_docs: 100000
    run_id: 1222
params:
  match_threshold: 75
