flows:
  classifier_train:
    --config: '{"encode": {"add_special_tokens": true, "max_length": 64, "pad_to_max_length":
      true, "return_token_type_ids": true, "return_attention_mask": true, "return_overflowing_tokens":
      false, "return_special_tokens_mask": false}, "model": {"pretrained_model_name_or_path":
      "distilbert-base-uncased", "return_dict": true}, "tokenizer": {"pretrained_model_name_or_path":
      "distilbert-base-uncased"}, "training_args": {"output_dir": "/Users/grichardson/nesta/industrial-taxonomy/models/",
      "learning_rate": 1e-05, "num_train_epochs": 1, "per_device_train_batch_size":
      8, "per_device_eval_batch_size": 16, "warmup_steps": 500, "weight_decay": 0.01,
      "logging_dir": "./logs", "logging_steps": 100, "save_total_limit": 2}, "train_val_test_split":
      {"train_size": 0.5, "val_size": 0.2, "test_size": 0.3, "random_state": 42}}'
    --documents_path: /Users/grichardson/nesta/industrial-taxonomy/data/raw/train_sample.json
    --freeze_model: 'False'
    run_id: 1096
  companies_house:
    run_id: 890
  glass:
    run_id: 414
params:
  match_threshold: 60
