flows:
  companies_house:
    run_id: 890
  glass:
    run_id: 414
  nlp_flow:
    params:
      # Can redefine the entities to be detected, by uncommenting below setting
      # entity_mappings:
      #   ORG: ORGANISATION
      # n_docs: 10000
      n_gram: 2
      n_process: 2
    run_id: 1619186850421496
params:
  match_threshold: 60
