flows:
  classifier_train:
    config:
      encode:
        add_special_tokens: true
        max_length: 64
        pad_to_max_length: true
        return_attention_mask: true
        return_overflowing_tokens: false
        return_special_tokens_mask: false
        return_token_type_ids: true
      model:
        pretrained_model_name_or_path: distilbert-base-uncased
        return_dict: true
      tokenizer:
        pretrained_model_name_or_path: distilbert-base-uncased
      train_val_test_split:
        random_state: 42
        test_size: 0.3
        train_size: 0.5
        val_size: 0.2
      training_args:
        learning_rate: 1.0e-05
        logging_dir: ./logs
        logging_steps: 100
        num_train_epochs: 1
        output_dir: /Users/George/nesta/industrial-taxonomy/models/
        per_device_eval_batch_size: 16
        per_device_train_batch_size: 8
        save_total_limit: 2
        warmup_steps: 500
        weight_decay: 0.01
    documents_path: /Users/George/nesta/industrial-taxonomy/data/raw/train_sample.json
    freeze_model: 'False'
    run_id: 1096
  companies_house:
    run_id: 890
  glass:
    run_id: 414
params:
  match_threshold: 60
