flows:
  companies_house:
    run_id: 890
  glass:
    run_id: 414
  nlp_flow:
    params:
      n-gram: 3
      n-process: 2
    run_id: 1111
params:
  match_threshold: 75
extraction:
  keybert:
    use_maxsum: True
  sample:
    sample_size: 10000
  industries:
    - category: sic4
      code: 6201
    - category: sic4
      code: 7490
taxonomy_test:
  test_file: description_kws_6201_7490
